from __future__ import annotations

import time
from collections.abc import Mapping
from typing import Any
from urllib.parse import urlencode

import requests

from config.settings import settings


class BackendHttpTransport:
    """
    HTTP transport used by the ParaBank service layer.

    Modes:
        direct:
            Client -> ParaBank

        proxy:
            Client -> Scrape.do -> ParaBank

        auto:
            Client -> ParaBank
            fallback to Scrape.do on HTTP 403/429

    Scrape.do remains an infrastructure concern and is
    invisible to features, steps and Page Objects.
    """

    FALLBACK_STATUS_CODES = {
        403,
        429,
    }

    SCRAPE_DO_RETRY_BACKOFF = (
        0.5,
        1.0,
        2.0,
    )

    DEFAULT_API_HEADERS = {
        "Accept": "application/json",
        "User-Agent": "parabank-automation-bdd/1.0",
    }

    def __init__(self) -> None:
        self.mode = settings.BACKEND_TRANSPORT
        self.timeout = settings.REQUEST_TIMEOUT_SECONDS

        self.scrape_do_api_url = (
            settings.SCRAPE_DO_API_URL.rstrip("/")
            + "/"
        )

        self.scrape_do_token = (
            settings.scrape_do_token
        )

        self.direct_session = requests.Session()

        self.direct_session.headers.update(
            self.DEFAULT_API_HEADERS
        )

        self.proxy_session = requests.Session()

    @property
    def proxy_available(self) -> bool:
        return bool(
            self.scrape_do_token
        )

    @staticmethod
    def _target_url(
        url: str,
        params: Mapping[str, Any] | None = None,
    ) -> str:
        """
        Builds the final ParaBank URL.

        Scrape.do receives the destination in its own
        `url` parameter, so ParaBank query parameters
        need to be encoded into that URL.
        """

        if not params:
            return url

        query = urlencode(
            params,
            doseq=True,
        )

        separator = (
            "&"
            if "?" in url
            else "?"
        )

        return (
            f"{url}"
            f"{separator}"
            f"{query}"
        )

    @staticmethod
    def _mark_transport(
        response: requests.Response,
        transport: str,
        target_url: str,
    ) -> requests.Response:
        """
        Adds diagnostic information and removes the
        Scrape.do request URL from the Response object.

        The provider URL contains the authentication
        token, so it must never appear in logs generated
        by raise_for_status().
        """

        response.url = target_url

        response.headers[
            "X-Test-Transport"
        ] = transport

        if response.request is not None:
            response.request.url = target_url

        return response

    @staticmethod
    def _is_scrape_do_rate_limit(
        response: requests.Response,
    ) -> bool:
        """
        Identifies HTTP 429 generated by Scrape.do itself,
        rather than HTTP 429 generated by ParaBank.
        """

        if response.status_code != 429:
            return False

        try:
            payload = response.json()
        except ValueError:
            return False

        if not isinstance(
            payload,
            dict,
        ):
            return False

        provider_url = str(
            payload.get(
                "URL",
                "",
            )
        ).lower()

        raw_message = payload.get(
            "Message",
            [],
        )

        if isinstance(
            raw_message,
            list,
        ):
            message = " ".join(
                str(item)
                for item in raw_message
            ).lower()
        else:
            message = str(
                raw_message
            ).lower()

        return (
            "scrape.do"
            in provider_url
            or "sending too fast"
            in message
        )

    @staticmethod
    def _is_scrape_do_provider_error(
        response: requests.Response,
    ) -> bool:
        """
        Identifies provider errors such as invalid token,
        exhausted plan or Scrape.do concurrency limits.
        """

        if response.status_code not in {
            400,
            401,
            402,
            403,
            407,
            429,
        }:
            return False

        try:
            payload = response.json()
        except ValueError:
            return False

        if not isinstance(
            payload,
            dict,
        ):
            return False

        provider_url = str(
            payload.get(
                "URL",
                "",
            )
        ).lower()

        possible_causes = str(
            payload.get(
                "PossibleCauses",
                "",
            )
        ).lower()

        contact = str(
            payload.get(
                "Contact",
                "",
            )
        ).lower()

        return (
            "scrape.do" in provider_url
            or "scrape.do" in possible_causes
            or "scrape.do" in contact
        )

    def request_direct(
        self,
        method: str,
        url: str,
        *,
        params: Mapping[str, Any] | None = None,
        data: (
            Mapping[str, Any]
            | str
            | bytes
            | None
        ) = None,
        headers: Mapping[str, str] | None = None,
        session: requests.Session | None = None,
    ) -> requests.Response:
        """
        Performs a request directly against ParaBank.
        """

        http_session = (
            session
            or self.direct_session
        )

        response = http_session.request(
            method=method,
            url=url,
            params=params,
            data=data,
            headers=headers,
            timeout=self.timeout,
        )

        return self._mark_transport(
            response=response,
            transport="direct",
            target_url=response.url,
        )

    def _perform_proxy_request(
        self,
        method: str,
        *,
        scrape_params: dict[str, Any],
        data: (
            Mapping[str, Any]
            | str
            | bytes
            | None
        ),
        target_headers: dict[str, str],
    ) -> requests.Response:
        """
        Executes the request through Scrape.do.

        Retries only when the 429 was generated by the
        Scrape.do concurrency limit.

        ParaBank responses are never blindly replayed.
        """

        response: requests.Response | None = None

        total_attempts = (
            len(
                self.SCRAPE_DO_RETRY_BACKOFF
            )
            + 1
        )

        for attempt in range(
            total_attempts
        ):
            response = (
                self.proxy_session.request(
                    method=method,
                    url=self.scrape_do_api_url,
                    params=scrape_params,
                    data=data,
                    headers=target_headers,
                    timeout=self.timeout,
                )
            )

            if not self._is_scrape_do_rate_limit(
                response
            ):
                break

            if (
                attempt
                >= len(
                    self.SCRAPE_DO_RETRY_BACKOFF
                )
            ):
                break

            delay = (
                self
                .SCRAPE_DO_RETRY_BACKOFF[
                    attempt
                ]
            )

            print(
                "[backend] Scrape.do "
                "concurrency limit reached; "
                f"retrying in {delay}s."
            )

            time.sleep(
                delay
            )

        if response is None:
            raise RuntimeError(
                "Scrape.do request did not "
                "produce a response."
            )

        return response

    def request_proxy(
        self,
        method: str,
        url: str,
        *,
        params: Mapping[str, Any] | None = None,
        data: (
            Mapping[str, Any]
            | str
            | bytes
            | None
        ) = None,
        headers: Mapping[str, str] | None = None,
        session_id: int | None = None,
        target_cookies: str | None = None,
    ) -> requests.Response:
        """
        Performs a request through Scrape.do API Mode.

        By default, REST calls explicitly request JSON:

            Accept: application/json

        Callers can override that header when necessary.
        Registration, for example, explicitly requests HTML.
        """

        if not self.scrape_do_token:
            raise RuntimeError(
                "Scrape.do transport was requested, "
                "but SCRAPE_DO_TOKEN is not configured."
            )

        target_url = self._target_url(
            url,
            params,
        )

        scrape_params: dict[
            str,
            Any,
        ] = {
            "token": self.scrape_do_token,
            "url": target_url,

            # Required so our Accept/User-Agent/etc.
            # reach ParaBank.
            "customHeaders": "true",

            "transparentResponse": "true",
        }

        if session_id is not None:
            scrape_params[
                "sessionId"
            ] = session_id

        # REST defaults.
        #
        # Explicit caller headers take precedence,
        # allowing register_user() to replace
        # Accept: application/json with text/html.
        target_headers = {
            **self.DEFAULT_API_HEADERS,
            **dict(
                headers
                or {}
            ),
        }

        if target_cookies:
            target_headers[
                "Cookie"
            ] = target_cookies

        response = (
            self._perform_proxy_request(
                method=method,
                scrape_params=scrape_params,
                data=data,
                target_headers=target_headers,
            )
        )

        # Remove provider URL/token before any exception
        # can be generated.
        response = self._mark_transport(
            response=response,
            transport="scrape.do",
            target_url=target_url,
        )

        if self._is_scrape_do_provider_error(
            response
        ):
            if self._is_scrape_do_rate_limit(
                response
            ):
                raise RuntimeError(
                    "Scrape.do concurrency limit "
                    "was reached after all retry "
                    "attempts."
                )

            raise RuntimeError(
                "Scrape.do rejected the proxy "
                "request. "
                f"HTTP {response.status_code}. "
                "Check SCRAPE_DO_TOKEN, credits "
                "and proxy configuration."
            )

        return response

    def request(
        self,
        method: str,
        url: str,
        *,
        params: Mapping[str, Any] | None = None,
        data: (
            Mapping[str, Any]
            | str
            | bytes
            | None
        ) = None,
        headers: Mapping[str, str] | None = None,
    ) -> requests.Response:
        """
        Executes according to BACKEND_TRANSPORT.

        proxy:
            Scrape.do -> ParaBank

        direct:
            Client -> ParaBank

        auto:
            Client -> ParaBank

            HTTP 403/429
                  ↓
            Scrape.do -> ParaBank
        """

        if self.mode == "proxy":
            return self.request_proxy(
                method,
                url,
                params=params,
                data=data,
                headers=headers,
            )

        direct_response = (
            self.request_direct(
                method,
                url,
                params=params,
                data=data,
                headers=headers,
            )
        )

        if self.mode == "direct":
            return direct_response

        should_fallback = (
            direct_response.status_code
            in self.FALLBACK_STATUS_CODES
        )

        if (
            should_fallback
            and self.proxy_available
        ):
            print(
                "[backend] "
                f"{method.upper()} {url} "
                "was blocked with HTTP "
                f"{direct_response.status_code}; "
                "retrying through Scrape.do."
            )

            return self.request_proxy(
                method,
                url,
                params=params,
                data=data,
                headers=headers,
            )

        return direct_response