from __future__ import annotations

import time
from collections.abc import Mapping
from typing import Any
from urllib.parse import urlencode

import requests

from config.settings import settings


class BackendHttpTransport:
    """
    HTTP transport used by the ParaBank service layer.

    Modes:
        direct:
            Client -> ParaBank

        proxy:
            Client -> Scrape.do -> ParaBank

        auto:
            Client -> ParaBank
            fallback to Scrape.do on HTTP 403/429

    Scrape.do remains an infrastructure concern and is
    invisible to features, steps and Page Objects.
    """

    FALLBACK_STATUS_CODES = {
        403,
        429,
    }

    # Backoff utilizado quando o próprio Scrape.do informa
    # que o limite de concorrência foi atingido.
    SCRAPE_DO_RETRY_BACKOFF = (
        0.5,
        1.0,
        2.0,
    )

    # Backoff para falhas transitórias de rede.
    #
    # É usado somente para métodos idempotentes.
    NETWORK_RETRY_BACKOFF = (
        1.0,
        2.0,
    )

    IDEMPOTENT_METHODS = {
        "GET",
        "HEAD",
        "OPTIONS",
    }

    DEFAULT_API_HEADERS = {
        "Accept": "application/json",
        "User-Agent": "parabank-automation-bdd/1.0",
    }

    def __init__(self) -> None:
        self.mode = settings.BACKEND_TRANSPORT

        self.timeout = (
            settings.REQUEST_TIMEOUT_SECONDS
        )

        self.scrape_do_api_url = (
            settings.SCRAPE_DO_API_URL.rstrip("/")
            + "/"
        )

        self.scrape_do_token = (
            settings.scrape_do_token
        )

        self.direct_session = requests.Session()

        self.direct_session.headers.update(
            self.DEFAULT_API_HEADERS
        )

        self.proxy_session = requests.Session()

    @property
    def proxy_available(self) -> bool:
        return bool(
            self.scrape_do_token
        )

    @staticmethod
    def _target_url(
        url: str,
        params: Mapping[str, Any] | None = None,
    ) -> str:
        """
        Builds the final ParaBank URL.

        Scrape.do receives the destination in its own
        `url` parameter, so ParaBank query parameters
        need to be encoded into that URL.
        """

        if not params:
            return url

        query = urlencode(
            params,
            doseq=True,
        )

        separator = (
            "&"
            if "?" in url
            else "?"
        )

        return (
            f"{url}"
            f"{separator}"
            f"{query}"
        )

    @staticmethod
    def _mark_transport(
        response: requests.Response,
        transport: str,
        target_url: str,
    ) -> requests.Response:
        """
        Adds diagnostic information and removes the
        Scrape.do request URL from the Response object.

        The provider URL contains the authentication
        token, so it must never appear in logs generated
        by raise_for_status().
        """

        response.url = target_url

        response.headers[
            "X-Test-Transport"
        ] = transport

        if response.request is not None:
            response.request.url = target_url

        return response

    @staticmethod
    def _is_scrape_do_rate_limit(
        response: requests.Response,
    ) -> bool:
        """
        Identifies HTTP 429 generated by Scrape.do itself,
        rather than HTTP 429 generated by ParaBank.
        """

        if response.status_code != 429:
            return False

        try:
            payload = response.json()
        except ValueError:
            return False

        if not isinstance(
            payload,
            dict,
        ):
            return False

        provider_url = str(
            payload.get(
                "URL",
                "",
            )
        ).lower()

        raw_message = payload.get(
            "Message",
            [],
        )

        if isinstance(
            raw_message,
            list,
        ):
            message = " ".join(
                str(item)
                for item in raw_message
            ).lower()
        else:
            message = str(
                raw_message
            ).lower()

        return (
            "scrape.do"
            in provider_url
            or "sending too fast"
            in message
        )

    @staticmethod
    def _is_scrape_do_provider_error(
        response: requests.Response,
    ) -> bool:
        """
        Identifies provider errors such as invalid token,
        exhausted plan or Scrape.do concurrency limits.
        """

        if response.status_code not in {
            400,
            401,
            402,
            403,
            407,
            429,
        }:
            return False

        try:
            payload = response.json()
        except ValueError:
            return False

        if not isinstance(
            payload,
            dict,
        ):
            return False

        provider_url = str(
            payload.get(
                "URL",
                "",
            )
        ).lower()

        possible_causes = str(
            payload.get(
                "PossibleCauses",
                "",
            )
        ).lower()

        contact = str(
            payload.get(
                "Contact",
                "",
            )
        ).lower()

        return (
            "scrape.do" in provider_url
            or "scrape.do" in possible_causes
            or "scrape.do" in contact
        )

    @classmethod
    def _can_retry_network_error(
        cls,
        method: str,
    ) -> bool:
        """
        Network retries are only permitted for HTTP
        methods that can safely be replayed.

        This prevents operations such as registration
        or fund transfer POSTs from being executed twice.
        """

        return (
            method.upper()
            in cls.IDEMPOTENT_METHODS
        )

    def request_direct(
        self,
        method: str,
        url: str,
        *,
        params: Mapping[str, Any] | None = None,
        data: (
            Mapping[str, Any]
            | str
            | bytes
            | None
        ) = None,
        headers: Mapping[str, str] | None = None,
        session: requests.Session | None = None,
    ) -> requests.Response:
        """
        Performs a request directly against ParaBank.
        """

        http_session = (
            session
            or self.direct_session
        )

        response = http_session.request(
            method=method,
            url=url,
            params=params,
            data=data,
            headers=headers,
            timeout=self.timeout,
        )

        return self._mark_transport(
            response=response,
            transport="direct",
            target_url=response.url,
        )

    def _perform_proxy_request(
        self,
        method: str,
        *,
        scrape_params: dict[str, Any],
        data: (
            Mapping[str, Any]
            | str
            | bytes
            | None
        ),
        target_headers: dict[str, str],
    ) -> requests.Response:
        """
        Executes a request through Scrape.do.

        Retry policies:

        1. Scrape.do concurrency HTTP 429:
           safe to retry because the provider rejected
           the request before it could be processed.

        2. Network timeout / connection errors:
           retry only when the original HTTP method is
           idempotent, such as GET.

        POST requests are never replayed because a timeout
        does not prove that the upstream server failed to
        process the operation.
        """

        method_upper = method.upper()

        rate_limit_retry = 0
        network_retry = 0

        while True:
            try:
                response = (
                    self.proxy_session.request(
                        method=method_upper,
                        url=self.scrape_do_api_url,
                        params=scrape_params,
                        data=data,
                        headers=target_headers,
                        timeout=self.timeout,
                    )
                )

            except (
                requests.Timeout,
                requests.ConnectionError,
            ) as exc:
                can_retry = (
                    self._can_retry_network_error(
                        method_upper
                    )
                )

                retries_exhausted = (
                    network_retry
                    >= len(
                        self.NETWORK_RETRY_BACKOFF
                    )
                )

                if (
                    not can_retry
                    or retries_exhausted
                ):
                    raise

                delay = (
                    self.NETWORK_RETRY_BACKOFF[
                        network_retry
                    ]
                )

                network_retry += 1

                print(
                    "[backend] Scrape.do "
                    f"{type(exc).__name__} during "
                    f"{method_upper}; "
                    f"retry {network_retry}/"
                    f"{len(self.NETWORK_RETRY_BACKOFF)} "
                    f"in {delay}s."
                )

                time.sleep(
                    delay
                )

                continue

            if not self._is_scrape_do_rate_limit(
                response
            ):
                return response

            retries_exhausted = (
                rate_limit_retry
                >= len(
                    self.SCRAPE_DO_RETRY_BACKOFF
                )
            )

            if retries_exhausted:
                return response

            delay = (
                self.SCRAPE_DO_RETRY_BACKOFF[
                    rate_limit_retry
                ]
            )

            rate_limit_retry += 1

            print(
                "[backend] Scrape.do "
                "concurrency limit reached; "
                f"retry {rate_limit_retry}/"
                f"{len(self.SCRAPE_DO_RETRY_BACKOFF)} "
                f"in {delay}s."
            )

            time.sleep(
                delay
            )

    def request_proxy(
        self,
        method: str,
        url: str,
        *,
        params: Mapping[str, Any] | None = None,
        data: (
            Mapping[str, Any]
            | str
            | bytes
            | None
        ) = None,
        headers: Mapping[str, str] | None = None,
        session_id: int | None = None,
        target_cookies: str | None = None,
    ) -> requests.Response:
        """
        Performs a request through Scrape.do API Mode.

        By default, REST calls explicitly request JSON:

            Accept: application/json

        Callers can override that header when necessary.
        Registration, for example, explicitly requests HTML.
        """

        if not self.scrape_do_token:
            raise RuntimeError(
                "Scrape.do transport was requested, "
                "but SCRAPE_DO_TOKEN is not configured."
            )

        target_url = self._target_url(
            url,
            params,
        )

        scrape_params: dict[
            str,
            Any,
        ] = {
            "token": self.scrape_do_token,
            "url": target_url,

            # Required so Accept/User-Agent/etc.
            # reach ParaBank.
            "customHeaders": "true",

            "transparentResponse": "true",
        }

        if session_id is not None:
            scrape_params[
                "sessionId"
            ] = session_id

        target_headers = {
            **self.DEFAULT_API_HEADERS,
            **dict(
                headers
                or {}
            ),
        }

        if target_cookies:
            target_headers[
                "Cookie"
            ] = target_cookies

        response = (
            self._perform_proxy_request(
                method=method,
                scrape_params=scrape_params,
                data=data,
                target_headers=target_headers,
            )
        )

        # Remove provider URL/token before any exception
        # can be generated.
        response = self._mark_transport(
            response=response,
            transport="scrape.do",
            target_url=target_url,
        )

        if self._is_scrape_do_provider_error(
            response
        ):
            if self._is_scrape_do_rate_limit(
                response
            ):
                raise RuntimeError(
                    "Scrape.do concurrency limit "
                    "was reached after all retry "
                    "attempts."
                )

            raise RuntimeError(
                "Scrape.do rejected the proxy "
                "request. "
                f"HTTP {response.status_code}. "
                "Check SCRAPE_DO_TOKEN, credits "
                "and proxy configuration."
            )

        return response

    def request(
        self,
        method: str,
        url: str,
        *,
        params: Mapping[str, Any] | None = None,
        data: (
            Mapping[str, Any]
            | str
            | bytes
            | None
        ) = None,
        headers: Mapping[str, str] | None = None,
    ) -> requests.Response:
        """
        Executes according to BACKEND_TRANSPORT.

        proxy:
            Scrape.do -> ParaBank

            Em caso de timeout/conexão:
            operações idempotentes podem fazer fallback
            direto para ParaBank.

        direct:
            Client -> ParaBank

        auto:
            Client -> ParaBank

            HTTP 403/429
                  ↓
            Scrape.do -> ParaBank
        """

        # ====================================================
        # PROXY MODE
        # ====================================================

        if self.mode == "proxy":
            try:
                return self.request_proxy(
                    method,
                    url,
                    params=params,
                    data=data,
                    headers=headers,
                )

            except (
                requests.Timeout,
                requests.ConnectionError,
            ) as proxy_exc:
                method_upper = method.upper()

                # Somente operações seguras para repetição
                # podem fazer fallback direto.
                if (
                    method_upper
                    not in self.IDEMPOTENT_METHODS
                ):
                    raise

                print(
                    "[backend] Scrape.do became "
                    "unavailable after all retries "
                    f"for {method_upper} {url}. "
                    "Trying direct read against ParaBank."
                )

                try:
                    return self.request_direct(
                        method,
                        url,
                        params=params,
                        data=data,
                        headers=headers,
                    )

                except (
                    requests.Timeout,
                    requests.ConnectionError,
                ) as direct_exc:
                    raise RuntimeError(
                        "Backend read failed through both "
                        "Scrape.do and direct ParaBank access. "
                        f"Operation: {method_upper} {url}. "
                        "Scrape.do error: "
                        f"{type(proxy_exc).__name__}. "
                        "Direct error: "
                        f"{type(direct_exc).__name__}."
                    ) from direct_exc

        # ====================================================
        # DIRECT / AUTO MODE
        # ====================================================

        direct_response = (
            self.request_direct(
                method,
                url,
                params=params,
                data=data,
                headers=headers,
            )
        )

        if self.mode == "direct":
            return direct_response

        # ====================================================
        # AUTO FALLBACK
        # ====================================================

        should_fallback = (
            direct_response.status_code
            in self.FALLBACK_STATUS_CODES
        )

        if (
            should_fallback
            and self.proxy_available
        ):
            print(
                "[backend] "
                f"{method.upper()} {url} "
                "was blocked with HTTP "
                f"{direct_response.status_code}; "
                "retrying through Scrape.do."
            )

            return self.request_proxy(
                method,
                url,
                params=params,
                data=data,
                headers=headers,
            )

        return direct_response